### ISSUE TITLE
add usage documentation

### ISSUE THREAD

**Issue by daylinmorgan** [daylinmorgan/viv#9]
A number of important configuration switches and use cases are not appropriately documented.

Some of the configuration switches as environment variables
```sh
VIV_NO_SETUPTOOLS
VIV_VERBOSE
VIV_CACHE
VIV_DEBUG
```

**Comment by TheShiveshNetwork** [comment]
If this is still open, assign this to me, I'd like to work on this!

**Comment by daylinmorgan** [comment]
Sure, if you think you understand these features well enough to describe them you can add to [docs/usage.md](https://github.com/daylinmorgan/viv/blob/main/docs/usage.md). The docs can generated locally using `nox -s docs` which will launch `sphinx-autobuild`.
